### PR TITLE
Part 1

### PR DESCRIPTION
**Pull request by Armenvardanyan95**
So this is a draft for the revised part 1, I have changed the title, fixed typos, added some more detailed explanations, and also fixed the code examples. Waiting for your thoughts

### CODE REVIEW

**Comment by LayZeeDK** [comment]
@Armenvardanyan95 is it possible to keep changes for `part-1.md` in a separate branch?

**Comment by Armenvardanyan95** [comment]
@LayZeeDK what do you mean? It is in a separate branch, no?

**Comment by LayZeeDK** [comment]
@Armenvardanyan95 This branch also contains changes for Part 3.

**Comment by Armenvardanyan95** [comment]
Closing this as another PR will open for it from the branch of this particular repo instead of my fork

**Pull request closed without merging**
